name: Test GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test permissions
        run: |
          echo "✅ GitHub Actions работает"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          
      - name: List files
        run: |
          echo "📁 Содержимое репозитория:"
          ls -la
          echo ""
          echo "📁 Содержимое .github:"
          ls -la .github/
