name: Test Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build
        run: |
          mkdir -p docs
          cp index.html docs/
          cp telegram-app.html docs/
          cp README.md docs/
          cp CNAME docs/
          touch docs/.nojekyll
          echo "✅ Тестовый сайт собран"
          ls -la docs/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          
      - name: Deploy
        uses: actions/deploy-pages@v4
